#!/usr/bin/env bash
#display hours from 0 to 12
#display i from 1 to 59

k=0

while [ $k -le 12 ]
do
    echo "Hour: $k"
    i=1
    while [ $i -lt 60 ]
    do
	echo "$i"
	((i++))
    done
    ((k++))
done
